### ISSUE TITLE
Check selection in BinaryGenAlgSolver

### ISSUE THREAD

**Issue by mikeliux** [diogomatoschaves/geneal#1]
I report possible problems with selection step for BinaryGenAlgSolver.

It seems like there is no improvement after a few iterations. 

For example, try to solve this objective function:

```
def fobj_test(x):
    answer = np.array([0]*300 + [1]*200)

    return -sum(abs(x-answer))
```

Here is the solver configuration:

```
solver = BinaryGenAlgSolver(
    n_genes = 500, # number of variables defining the problem
    fitness_function = fobj_test, # fitness function to be maximized
    max_gen = 1000,
    mutation_rate = 0.25,
    selection_rate = 0.5,
    pop_size = 50,
    selection_strategy = "roulette_wheel")
```

Below you can fin the results. The maximum of this fitness function would be 0,  but the best fitness is frozen at -184 within the first generations..

Notice: I am using a different initialize_population method, which I will describe in another issue.

![image](https://user-images.githubusercontent.com/61921085/89715360-de721280-d96a-11ea-8968-0c1c8df9f1ef.png)

**Comment by mikeliux** [comment]
I noticed I just had to use a lower mutation_rate , such as 0.005. Then it will evolve in the desired direction. 
Sorry

**Comment by diogomatoschaves** [comment]
Hi @mikeliux, thanks for the feedback. Yes, the mutation rate plays a big role in the convergence, and if it's too high or too low it can prevent the run to converge.

I'm a bit puzzled by your graph tough, as the `max fitness` should not fluctuate as shown. Due to elitism (the fact that we always keep the best result), the maximum fitness should never decrease. Did you modify anything related to this?
