### ISSUE TITLE
Is there any way to put constraints on variables?

### ISSUE THREAD

**Issue by SiddhiMali** [diogomatoschaves/geneal#10]
For example, summation of all genes must be equal to 1

**Comment by diogomatoschaves** [comment]
Hi @SiddhiMali, apart from limiting each individual gene to a certain interval, currently there is not a hard and fast way of doing that. In order to achieve it, you would have to override all the 3 main methods of the solver (*initialize_population*,  *create_offspring*, *mutate_population*), and impose those constraints whenever a chromossome is created, crossed over or mutated.
